### TESTING
TESTING: false # Load as little as possible for fast prototyping
SMALL_TRAINING: false
plot_freq: 50
images_to_load: 20
## Things that shouldn't matter much:
# Random shuffling
# Number of channels (3 vs 1)
# Batch figsize 8 vs 16

# Load model
load_path: false # ./results/baseline/20190622_155031-lr_0.001_bs_16_warp_False_arch_basic_encoder/baseline_model.pt # or false
#load_path: /media/data/GitHub/simple_hwr/results/baseline/20190625_092305-lr_0.001_bs_16_warp_True_arch_basic_encoder/baseline_model.pt
test_only: false                             # Do not train

# General
experiment: baseline
name_deprecated: true_baseline
output_folder: ./results
epochs_to_run: 200
save_freq: 1
use_visdom: true
debug: off

# results_dir:
# log_dir:

# Training data
training_jsons: [online_coordinate_data/MAX_stroke_vNORMAL_TRAINING_TESTFull/train_online_coords.json]
training_root: data # RELATIVE TO PROJECT ROOT
training_shuffle: true
training_warp: false
training_blur: false
training_random_distortions: false
online_augmentation: true
writer_id_pickles: [prepare_IAM_Lines/writer_IDs.pickle, prepare_online_data/writer_IDs.pickle]

# Validation
validation_jsons: []

# Testing data
testing_jsons: [online_coordinate_data/MAX_stroke_vNORMAL_TRAINING_TESTFull/test_online_coords.json]
testing_root: data
testing_shuffle: false
testing_warp: false
testing_blur: false
testing_random_distortions: false
output_predictions: false                    # Output incorrect test predictions

#Network
style_encoder: false                         # "False", "basic_encoder", "fake_encoder" - RNN + MLP (author classifier) -> embedding
batch_size: 16                               # Batch figsize
input_height: 60                             # Input dimension of image (will be cropped by default?)
cnn_out_size: 1024                           # Output dimension of CNN
num_of_channels: 1                           # Number of channels in input image
rnn_dimension: 512                           # originally 512

# Recognizer parameters
recognizer_dropout: .5                       # Dropout in recognizer LSTM

# Writer Classifier - LSTM + MLP (with embedding layer)
writer_dropout: 0.4                          # Probability of being "dropped out" in writer LSTM+MLP
writer_rnn_dimension: 128                    # Dimension of LSTM state vector
writer_rnn_output_size: 256                  # LSTM output dimension for writer classifier
mlp_layers: [64,embedding,64]             # Layer dimensions for MLP writer classifier
embedding_size: 32                           # The figsize of the embedding layer in the MLP

# LR schedule
learning_rate: 5e-3          # LR
scheduler_step: 5         # Every X steps, multiply LR by gamma
scheduler_gamma: .95          # LR decay rate
